### PR TITLE
CSV Velocity

### PR DESCRIPTION
**Pull request by manuelgitgomes**
CSV velocity is recorded boolean while on real car and records twist while on gazebo. It functions on the real car and on my machine's gazebo. Can someone run the `roslaunch simulation_bringup traxxas_drive_write.launch folder:=setX` command and check is the .csv records the right velocity?

### CODE REVIEW

**Comment by brunomonteiro98** [comment]
I did a test now in gazebo and it just recorded the velocity as 0.5 despite me changing the speed while driving

**Comment by manuelgitgomes** [comment]
Try using the twist command `/cmd_vel` instead of `/cmd_velin`. The latter defaults any velocity larger than 0.1 to 0.5!

**Comment by brunomonteiro98** [comment]
It needs to record with the cmd_vel instead of cmd_velin to record the changes in velocity , otherwise it just writes 0.5 all the time. We can pull to dev

**Review by brunomonteiro98 — APPROVED** [review]
It works using the cmd_vel instead of cmd_velin

**Pull request merged**
